### ISSUE TITLE
Add support for build-args

### ISSUE THREAD

**Issue by gabe565** [whoan/docker-build-with-cache-action#10]
Currently passing `--build-arg` to the Docker call is not supported, but I could see that being a commonly used feature.

Are there any plans to add support for build-args? I can take a look soon.

**Comment by whoan** [comment]
Agree @gabe565 . That would be very useful. I can't work on it right now, so if you want to do it, please go ahead.

**Comment by whoan** [comment]
I will work on it @gabe565
