### ISSUE TITLE
Self-hosted runners and ECS

### ISSUE THREAD

**Issue by Sundin** [whoan/docker-build-with-cache-action#107]
Hi! We run our Github Actions on self-hosted runners (hosted on AWS). The runners themselves have access to the ECR registry where we store our Docker images, as demonstrated by step 3 in my example below. However, the docker-build-with-cache-action does not get access, presumably because it runs inside a Docker environment which does not "inherit" the proper credentials. Maybe it has to do with that we don't want/need to have the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in our Github Secrets?

I tried to follow the examples in the documentation but maybe I've missed something here?

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # This works (just for debugging puposes):
      - run: aws ecr list-images --repository-name my-image
        shell: bash

      - uses: whoan/docker-build-with-cache-action@v5
        with:
          registry: 134918118666.dkr.ecr.eu-west-1.amazonaws.com
          context: src
          dockerfile: app/Dockerfile
          image_name: my-image

This is the error message I get:

```
[Action Step] Log in to registry...
INFO: Missing value USERNAME
No credentials provided
INFO: Won't be able to pull from private repos, nor to push to public/private repos
```

Don't know if this is even supposed to work on self-hosted runners or not, happy for any feedback! Thanks!

**Comment by whoan** [comment]
According to [configure-aws-credentials' docs](https://github.com/aws-actions/configure-aws-credentials#self-hosted-runners), when you use self-hosted runner that already has access to AWS credentials, the actions will use the runner's credentials which not necessarily be the env variables which this action is expecting.

I think we have two options here:

1. If you use `role-to-assume` in `aws-actions/configure-aws-credentials`, you'll have the env variables set for the next actions (eg; docker-build-with-cache-action). I would have to confirm this.
2. To make this action smarter and use other means to get credentials. From the link in the aforementioned reference, there are many methods to get credentials, but at least I could try to also get them from **.aws/credentials** (as a volume in the docker env aws-cli is running).

**Comment by aktech** [comment]
@Sundin By the way, if you want a no-maintenance method to achieve that, you can use [cirun.io](https://cirun.io) for the same.

**Comment by whoan** [comment]
Closing this as it can be solved simply by using `role-to-assume` so the env vars are set as explained in https://github.com/whoan/docker-build-with-cache-action/issues/107#issuecomment-1281583741
