### ISSUE TITLE
Set INPUT_SESSION=$AWS_SESSION_TOKEN if no input provided

### ISSUE THREAD

**Issue by emmaai** [whoan/docker-build-with-cache-action#108]
`INPUT_SESSION` can be only set by providing `session` atm. If login by `aws-actions/configure-aws-credentials` with assumed-role, the env variable `AWS_SESSION_TOKEN` is set. Currently it can grab all the other credential related info from env, it'd be great if grab an extra. Happy to pr on it.

**Comment by whoan** [comment]
Hi @emmaai I haven't had time to spend to spend on the action. Please submit a PR if you know how to do it and test it. Thanks.

**Comment by emmaai** [comment]
> Hi @emmaai I haven't had time to spend on the action. Please submit a PR if you know how to do it and test it. Thanks.

I was about to then realised I don't have access. Thanks for fixing it. :)
