### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by saintevil** [whoan/docker-build-with-cache-action#113]
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by rix1337** [comment]
@whoan could you release this so the deprecation notice disappears from our builds? 🙏🏻

**Comment by whoan** [comment]
I am waiting to be have some time to write more tests in https://github.com/whoan/hello-world repo (the one I use to test this action) and then I'll feel comfortable to release. I mainly need to learn how to set a role in AWS as I am not covering that in current tests.

In the meantime, as a workaround, I think you could use the hash of tip of master as the version in your workflow to use latest features:

     - uses: whoan/docker-build-with-cache-action@ed61253

Not very clean though... Let me try to get to it at the weekend.

**Comment by rix1337** [comment]
Thanks for the workaround @whoan 
I agree its not as clean but a last resort if the release takes longer.

Deprecation is scheduled for Summer 2023, so we can of course wait.

**Comment by cole-nayya** [comment]
hi @whoan - thanks for maintaining this! Is there a plan to release the new version with the set-output command removed?
