### ISSUE TITLE
Cache and Publish to seperate Registries/Repositories

### ISSUE THREAD

**Issue by rix1337** [whoan/docker-build-with-cache-action#117]
To keep my main Docker Hub account clean, I would love to push cached builds to a separate account or registry.

If that is possible right now, I did not manage to achieve it.
If that is not possible right now, I would love to see this implemented.

Thanks for your consideration @whoan !

**Comment by whoan** [comment]
HI @rix1337 . I have considered that feature in the past and the complication it brings is that we'd need a separate set of credentials to do so.
Let me think a little more about it though. Maybe it's worth it at the end.

**Comment by rix1337** [comment]
Okay, so I did not overlook something trying to set it up.

Complexity is a valid reason to not implement this, though.

**Comment by whoan** [comment]
Hi @rix1337 . What about pushing stages as different tags in the same repository?

**Comment by rix1337** [comment]
The main reason for this request is that my docker hub account is now cluttered with cache repos.

It's not bad, but just does not look clean ;)

**Comment by whoan** [comment]
Not going to implement this feature for the moment. Sorry.

**Comment by whoan** [comment]
Now with BuildKit enabled by default in [v8](https://github.com/whoan/docker-build-with-cache-action/tree/v8), I think you could try with S3 cache backend:

- Disable the automatic push with `pull_image_and_stages: false`
- Pass both `--push` and (for example) `--cache-to type=s3,<...>` through `build_extra_args`
- Login in advance (likely with another action) to wherever the cache will be saved

Link to Amazon S3 Cache backend for reference: https://docs.docker.com/build/cache/backends/s3/

-------

You could also use artifacts in this way:

- Choose a well known place for the cache (eg: ./my-cache)
- Disable the automatic push with `pull_image_and_stages: false`
- Use [download-artifact](https://github.com/actions/download-artifact) to get cache into ./my-cache
- Pass both `--push` and `--cache-to type=local,dest=my-cache` through `build_extra_args`
- Use [upload-artifact](https://github.com/actions/upload-artifact) to place cache into ./my-cache

Link to Local Cache backend for reference: https://docs.docker.com/build/cache/backends/local/
