### ISSUE TITLE
[Request] Publish Action image to `ghcr.io` instead of building on-the-fly

### ISSUE THREAD

**Issue by SimulatedGREG** [whoan/docker-build-with-cache-action#123]
Currently this Action requires the runner to create, although quickly, a local build of the image on-the-fly before the Action can be used. This works great for a majority of use cases.
![image](https://user-images.githubusercontent.com/8327811/220186408-56a6b802-959c-4f04-be15-1342865d3d44.png)

In my situation at work, this will timeout due to the default `network` mode that is used when building the image, as our self-hosted runner is very limited on what it has access to. As far as I can tell, there's no way to actually change this setting from the runner side.

Would it be possible to build this Action and publish it to `ghcr.io`, that way the action can simply be pulled instead? This method is proven to work on our self-hosted runners and will likely bring a slight speed increase (I'd guess a 2 second savings), such as in https://github.com/rtCamp/action-slack-notify/blob/master/action.yml#L6.
![image](https://user-images.githubusercontent.com/8327811/220186616-b581326c-26f1-462f-ba7e-1f1df472fd12.png)

**Comment by whoan** [comment]
I like the idea. I hope I can work on this at the week end.

**Comment by whoan** [comment]
I gave this a try  and I don't see a considerable saving between pulling and building from scratch. Sometimes, not improvement at all.
eg:

Building:

- https://github.com/whoan/hello-world/actions/runs/6678007438
- https://github.com/whoan/hello-world/actions/runs/6678007439
- https://github.com/whoan/hello-world/actions/runs/6678007440
- https://github.com/whoan/hello-world/actions/runs/6678007441

Pulling:

- https://github.com/whoan/hello-world/actions/runs/6679364487
- https://github.com/whoan/hello-world/actions/runs/6679364488
- https://github.com/whoan/hello-world/actions/runs/6679364489
- https://github.com/whoan/hello-world/actions/runs/6679364490

Given it would make maintenance a little harder for me, i am not sure I am going to implement this feature.
Will leave the issue open for a while in case there's some more interest/incentive to do it.
