### ISSUE TITLE
Fail to build rails app that rely on mimemagic

### ISSUE THREAD

**Issue by noxasch** [whoan/docker-build-with-cache-action#126]
As the title say since the build is run in another container from this action that based on alpine, it cause build to fail due to missing dependency.

Using raw `docker build` on github runner directly works fine.

```
Fetching mimemagic 0.3.9
Installing mimemagic 0.3.9 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/mimemagic-0.3.9/ext/mimemagic
/usr/local/bin/ruby -rrubygems
/usr/local/lib/ruby/gems/2.6.0/gems/rake-12.3.3/exe/rake
RUBYARCHDIR\=/usr/local/bundle/extensions/x86_64-linux/2.6.0/mimemagic-0.3.9
RUBYLIBDIR\=/usr/local/bundle/extensions/x86_64-linux/2.6.0/mimemagic-0.3.9
rake aborted!
Could not find MIME type database in the following locations:
["/usr/local/share/mime/packages/freedesktop.org.xml",
"/opt/homebrew/share/mime/packages/freedesktop.org.xml",
"/usr/share/mime/packages/freedesktop.org.xml"]

Ensure you have either installed the shared-mime-info package for your
distribution, or
obtain a version of freedesktop.org.xml and set FREEDESKTOP_MIME_TYPES_PATH to
the location
```

**Comment by whoan** [comment]
@noxasch Do you know which package is requiring mimemagic? I am not sure if that's something required for the action itself. That dependency is not familiar to me

**Comment by noxasch** [comment]
I'm using a gem to generate excel file [caxlsx](https://github.com/caxlsx/caxlsx), it include the mimemagic as one of dependencies.

**Comment by noxasch** [comment]
@whoan on my alpine image i based from ruby:alpine so it already have the require path. For custom alpine I think this will help https://stackoverflow.com/questions/69248078/mimemagic-install-error-could-not-find-mime-type-database-in-the-following-loc

**Comment by whoan** [comment]
OK @noxasch . That doesn't feel something to fix in this GH action then. I am closing this one. Thanks for the clarification.

**Comment by noxasch** [comment]
actually it need to be specify in this docker action image in order to run docker build. for me it's fine though since i no longer use this action. just heads up in case anyone else facing the same issue.
