### ISSUE TITLE
Is it possible to only build specific services from compose?

### ISSUE THREAD

**Issue by alexalok** [whoan/docker-build-with-cache-action#127]
First of all, thank you for creating and maintaining this action. It is of great help to me. 
I seem to have stepped into a limitation. I have a compose file defining multiple services, but I only want to build only a subset of them. Is this currently not a supported scenario?

**Comment by whoan** [comment]
I like the idea @alexalok . Not sure when I am going to be able to work on it but I will definitely put it on my list.
