### ISSUE TITLE
Suggestion: Ability to wrap a Docker Compose stack

### ISSUE THREAD

**Issue by Dzhuneyt** [whoan/docker-build-with-cache-action#13]
Some functionality suggestions:
* Ability to do the same thing that the action currently does - for all services within a Docker Compose yml file
* Ability to pull/push from a private AWS ECR repo

**Comment by whoan** [comment]
Thanks for the suggestions @Dzhuneyt . I think both of them would make the action more complex than expected so I am not interested in implementing them. eg: I don't want to install aws-cli only to login to AWS ECR (AFAIK it's the only way) but I can check this again in the future to see if there is a simpler way.

Feel free to submit a PR and we can discuss the trade-off.

Closing this for now.

**Comment by whoan** [comment]
@Dzhuneyt Just FYI, your suggestions have been finally implemented:

- Support for AWS ECR; https://github.com/whoan/docker-build-with-cache-action/pull/27
- Support for compose files: https://github.com/whoan/docker-build-with-cache-action/pull/78
