### ISSUE TITLE
build stages not being pushed

### ISSUE THREAD

**Issue by jilipop** [whoan/docker-build-with-cache-action#131]
We've been using v5 in a Github Action successfully for many months and it suddenly stopped pushing the build stages to ECR correctly, always only pushing the last stage with tag "1". I'm not aware of any relevant change on our side. The only thing I noticed is a more recent Github Actions runner version being used. Updating to docker-build-with-cache-action v6 didn't help.

I did a little digging and I think this is what's happening:

Apparently in your docker-build.sh the piping of the output in this code no longer works:
```
docker build \
    $cache_from \
    --tag "$DUMMY_IMAGE_NAME" \
    --file "${INPUT_CONTEXT}"/"${INPUT_DOCKERFILE}" \
    ${INPUT_BUILD_EXTRA_ARGS} \
    "${extra_args[@]}" \
    "${INPUT_CONTEXT}" | tee "$BUILD_LOG"
```

The build-output.log remains empty and _get_stages doesn't find any stages, so none get pushed, which in turn messes up our whole deployment.

Anyway, [sources on the internet](https://forums.docker.com/t/capture-ouput-of-docker-build-into-a-log-file/123178) say docker build no longer logs to standard output but rather to the standard error stream, so adding 2>&1 before the pipe operator should fix the problem. It does when I try to write docker build output to both the console and a file locally:

```
docker build . | tee test.log
```
--> full output in console, empty test.log

```
docker build . 2>&1 | tee test.log
```
--> full output in both console and test.log

**Comment by jilipop** [comment]
Okay, it's not that easy. I've forked this repo and tried the change. build-output.log now does get populated but the output is very different from before. Not sure if this is because of buildkit now being used.

**Comment by jilipop** [comment]
Yeah, it was because of buildkit. This did the trick for now:

```
- name: Build and push the Docker image
      env:
        DOCKER_BUILDKIT: 0
      uses: whoan/docker-build-with-cache-action@v5.0.0
      [...]
 ```
Might be could to add this to your examples.

There's a warning about this environment variable being deprecated, so this solution might not be permanent.

**Comment by whoan** [comment]
Now this works again even with BuildKit enabled in [v8](https://github.com/whoan/docker-build-with-cache-action/tree/v8)
