### ISSUE TITLE
Add option to push multiple tags.

### ISSUE THREAD

**Issue by vanneback** [whoan/docker-build-with-cache-action#14]
Feature Request.
Add option to specify more than one tag. For example i want to push a version tag and latest in one step.

**Comment by whoan** [comment]
I like the idea. I can work on it at the weekend. Thanks @vanneback 

Feel free to submit PR if in a hurry.

**Comment by whoan** [comment]
@vanneback If you have a git tag in the commit you are using to build, it will be also pushed, besides the tag you provide in `image_tag`. Doesn't that help?

**Comment by elderapo** [comment]
It would be awesome if it was possible to set `image_tag` option to multiple tags instead of just one ex:
```yml
with:
  image_tag: "latest,${{ env.DOCKER_IMAGE_SEMVER }}"
```

**Comment by vanneback** [comment]
Thanks for the fix @whoan!
