### ISSUE TITLE
Support cache mounts using reproducible-containers/buildkit-cache-dance

### ISSUE THREAD

**Issue by MC-Dave** [whoan/docker-build-with-cache-action#154]
Purpose: To allow for injecting caches into build layers. This can be helpful when, for example, one can use `ccache` to cache c-compilations, pull it out, then inject it in future builds to avoid re-compiling previously-compiled c code.

Reference: https://docs.docker.com/build/ci/github-actions/cache/#cache-mounts

This action has been extremely useful to me and my team. Wondering if you have any plans to support cache mounts, now that the majority of the buildkit issues have been resolved. 

Merry Christmas!

**Comment by whoan** [comment]
Hi @MC-Dave . Thanks for suggesting the improvement.
Let me try to investigate a little this weekend so I can come up with an answer for you.

Merry Christmas to you too!

**Comment by whoan** [comment]
@MC-Dave I was looking at this and seems like a lot of work and I don't have time these days.
If you know what should be done, feel free to explain here in comments so I can take a look again in some moment.
Thanks.

**Comment by MC-Dave** [comment]
@whoan No worries, I figured it would be alot of work to implement. 
If I get around to working it out myself I will be sure to update this issue with the details.

Thanks and happy new year!
