### ISSUE TITLE
Disable pull option

### ISSUE THREAD

**Issue by GrosQuildu** [whoan/docker-build-with-cache-action#18]
Cool actions, thanks for it.

But I wonder if there is option to build and push images without pulling them first from the repo? For one action run of course, just to rebuild images from scratch. Question due to the problem of running out of memory when both pulling old images and rebuilding new.

And I can't clear the registry manually, but why is a longs story ;)

**Comment by GrosQuildu** [comment]
See #19

**Comment by GrosQuildu** [comment]
Also may be useful with `if` statements in the workflow, i.e. to rebuild master once a week.

**Comment by whoan** [comment]
Closed by #19
