### ISSUE TITLE
Cannot be used for CI from forked repos

### ISSUE THREAD

**Issue by jackgerrits** [whoan/docker-build-with-cache-action#20]
This action requires a username and password to be used. However, GitHub actions does not support accessing secrets when building PRs from a fork. Therefore this action will fail to be used as a PR status check.

Since the password is only used for publishing to the cache is it possible to add support for just downloading and building from cache. Then the password would at least not be needed?

**Comment by whoan** [comment]
Good suggestion. Let me take a look at it in the following days. Thanks.
