### ISSUE TITLE
push_git_tag not working

### ISSUE THREAD

**Issue by shunkakinoki** [whoan/docker-build-with-cache-action#22]
First of all, thanks for the amazing action!
Was looking for the github action just like this,

My problem is that the `push_git_tag` option not working on publish.
Steps to reproduce:

workflow: https://github.com/shunkakinoki/notebook/runs/479346027?check_suite_focus=true
dockerhub: https://hub.docker.com/repository/docker/shunkakinoki/notebook/tags?page=1

**Comment by whoan** [comment]
Hi @shunkakinoki . Can't take a look now, but please be sure you are using latest version of the action (currently: v4) and the git tag needs to be in the last commit of the branch being built. I am pretty sure I tested it and it worked, but I can check again in about 8 hours.

Thanks for using this action.

**Comment by shunkakinoki** [comment]
hi @whoan thanks for the quick response!
it has to be in the `last commit of the branch`, missed this part!
resolved now, thanks for everything~
