### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by cmagorian** [whoan/docker-build-with-cache-action#30]
`Error response from daemon: login attempt to https://***/v2/ failed with status: 401 Unauthorized`

I've went ahead and ran the commands in `entrypoint.sh` manually to ensure that the credentials are valid. They are fine. 

Evaluation of the registry endpoint succeeds in determining that it is an ECR endpoint, so I should be falling into the right docker login with aws ecr. 

Not sure where else to look.

**Comment by ivosequeros** [comment]
Same issue here

**Comment by ivosequeros** [comment]
There seems to be an issue with the docker login.
https://aws.amazon.com/blogs/compute/authenticating-amazon-ecr-repositories-for-docker-cli-with-credential-helper/

**Comment by ivosequeros** [comment]
https://github.com/whoan/docker-build-with-cache-action/pull/32

**Comment by cmagorian** [comment]
Thanks @ivosequeros !
