### ISSUE TITLE
Build/cache in github, deploy to ECR

### ISSUE THREAD

**Issue by cranberyxl** [whoan/docker-build-with-cache-action#35]
Can I do the building and caching in Github registry and then push the final product to ECR?

**Comment by whoan** [comment]
@cranberyxl I think that would be a very good feature to have. I will work on this when I have some time. Maybe this weekend.

Thanks.

**Comment by abrkn** [comment]
I'm looking to do the same, but Github registry only gives me 2 GB under the Team plan.

**Comment by whoan** [comment]
I think the best approach would be to allow setting a different registry (any) for the stages, allowing to set username and password too. Maybe using more optional input:

- stages_username
- stages_password
- stages_registry

If they are not provided, it will use the same registry of the main image.

**Comment by whoan** [comment]
As I said, I think allowing only GitHub for the stages is not the way to go, for the current restrictions in the amount of data we can save.

Not doing for the moment as it would change the action code too much. I can take a look again for newer versions of the library if there are more people interested in this feature, which is a good one BTW.

I was also thinking about something more flexible like allowing _pre_ and _post_ scripts to run, so you can either (docker) `pull`/`push` respectively from any registry, as well as `load`/`save` from files downloaded/uploaded to s3 (for example).

Thanks for the suggestion @cranberyxl

**Comment by abrkn** [comment]
I've spent a lot of time working on stage caching for a CI/CD that had crept up to 30 minutes. I highly recommend storing layers on GitHub's registry. It's more expensive than others, but much quicker and you won't have to pay for traffic.
