### ISSUE TITLE
Add image identifier as an output

### ISSUE THREAD

**Issue by abrkn** [whoan/docker-build-with-cache-action#36]

**Comment by whoan** [comment]
Could you please add more information @abrkn ?

- Do you need what the function `_get_full_image_name` prints in entrypoint.sh script? as you provide the image name and registry (optional) to the action, I don't see why _returning_ the image identifier as an output would add value. But maybe I am just not getting what you mean by image identifier
- If you have a use case for this, that would be really helpful

Thanks

**Comment by whoan** [comment]
After some changes on master branch, now I see why using the image name as the output of the action might be useful. @abrkn please see if #38 is what you are looking for.

**Comment by whoan** [comment]
Closed by #38
