### ISSUE TITLE
Run container before publishing

### ISSUE THREAD

**Issue by asbjornu** [whoan/docker-build-with-cache-action#37]
This looks like a neat action, but I would like to test that the built container works before publishing it. Would it be possible to do `docker run` and only publish if that succeeds?

**Comment by whoan** [comment]
Maybe a new input like `publish_if` which allows you to run an arbitrary command would be a one-size-fits-all solution. I will think about it when I have some time.

Thanks for the suggestion.

**Comment by whoan** [comment]
@asbjornu You can now use the same `push_image_and_stages` tag to test a command before pushing (ie: it will push only if the command succeed):

    push_image_and_stages: docker run my_awesome_image:latest

**Comment by asbjornu** [comment]
Sounds great, @whoan! Thanks! 🙏
