### ISSUE TITLE
Cache not working

### ISSUE THREAD

**Issue by aledalgrande** [whoan/docker-build-with-cache-action#4]
I created a Dockerfile with 3 stages, successfully built and pushed to the Github registry inside a Gtihub action, but at the next run, without having invalidated any of the first layers (tested locally), the build started from scratch.

How does it work? Did I do something wrong?

**Comment by whoan** [comment]
Could I see your Dockerfile? Maybe it has something to do with the base image (`FROM` line). Try to be as specific as you can with the base image. eg: **alpine:3.10.1** instead of **alpine:latest**.

Do you see the stages also being pushed to the registry?

**Comment by aledalgrande** [comment]
Hey I actually managed to use cached docker layers without the need of adding an external action, by using the strategy indicated here: https://semaphoreci.com/docs/docker/docker-layer-caching.html

If I do that, it reuses layers correctly.

**Comment by whoan** [comment]
@aledalgrande I am happy you found the way to do it :)

Anyway, I am still curious why my action didn't work in your scenario. If you are using it in a public repo, could you share the link? So I can see if I find the way to make it work in those scenarios.

Thanks!

**Comment by aledalgrande** [comment]
Sorry, the repo is private and owned by my employer!

**Comment by whoan** [comment]
That might be invalidated the cache then. Thanks for the information @aledalgrande!

**Comment by hos** [comment]
Hi. First thank you for your work on this. Cache seems not working in my case can you help me with finding the reason?
 Here is the `Dockerfile`

```
FROM node:12.16.2-alpine3.11 AS client

WORKDIR /usr/src

# cache yarn install layer before build
COPY ./@app/client/package.json .
RUN yarn set version berry
RUN yarn config set nodeLinker node-modules
RUN yarn

COPY ./@app/client .

RUN yarn build

FROM node:12.16.2-alpine3.11 AS server

WORKDIR /usr/src

COPY ./@app/server/package.json ./@app/server/package.json
COPY ./@app/db/package.json ./@app/db/package.json
COPY ./package.json ./package.json

RUN yarn set version berry
RUN yarn config set nodeLinker node-modules
RUN yarn

COPY ./@app/db ./@app/db
COPY ./@app/server ./@app/server
COPY --from=client /usr/src/build ./@app/server/public

ENV BUILD_DIR=/usr/src/@app/server/public

# for health check install curl
RUN apk add --no-cache curl

CMD ["yarn", "server", "start"]
```

**Comment by whoan** [comment]
Hi @hos. Is it a public repo? So I can see the logs of the workflow. Can you see in which line you see the cache is not working? I mean, which is the last step where you see ` ---> Using cache` (if any)?

**Comment by hos** [comment]
It's private repo, but here is the [log file online](https://pipelines.actions.githubusercontent.com/wfQP6L2qgYmFfEawjiJaMaehA16aha0u0Mfg7TtccuVwh9DVGj/_apis/pipelines/1/runs/539/signedlogcontent/3?urlExpires=2020-04-12T23%3A54%3A51.7288172Z&urlSigningMethod=HMACV1&urlSignature=9hLLTbVinaM%2FYP7n%2FX16uH4C6NykUZ2frmpTL03v1P0%3D) and the downloaded [logs](https://file.io/ZOIKBX).
Do you think this is enough?

**Comment by whoan** [comment]
I am not being able to access those links: uri expired and 404 error. Could you double check please?

**Comment by hos** [comment]
Sorry about that. Please check [this one](https://wetransfer.com/downloads/39972e25d868a4a12ce16d2c0e6b370520200413011213/cb911e5081718deb08169a332c45f05b20200413011231/721068).

**Comment by whoan** [comment]
@hos Cache is working as I can see several **Using cache** lines. Then, in one layer, `./@app/server/package.json` file is invalidating further docker steps:

    2020-04-12T20:49:34.2917516Z Step 10/22 : WORKDIR /usr/src
    2020-04-12T20:49:35.1731575Z  ---> Using cache
    2020-04-12T20:49:35.1732343Z  ---> b06303a690fe
    2020-04-12T20:49:35.1732822Z Step 11/22 : COPY ./@app/server/package.json ./@app/server/package.json
    2020-04-12T20:49:43.7163997Z  ---> a2002cb04cac

This is expected whenever a file changes.

**Comment by hos** [comment]
@whoan Yes I see what you mean. But I just checked again, just changed only another js file and cache is still invalidated. Maybe this is not related to this package, instead I need to debug with docker itself to see why layers are changed?

**Comment by whoan** [comment]
@hos Exactly, you can even test it locally for faster feedback with `docker build` as you should see the same problem there. ie: not related to the action.

**Comment by hos** [comment]
Actually when I build locally it is using layers. So build takes few seconds. Maybe something with registry?

**Comment by whoan** [comment]
That is interesting. I don't have the answer now, but I would like to do some research to find out how that can happen. I can't dig further now, but I will let you know if I find the answer.

**Comment by hos** [comment]
Will update you with info if any. Thank you for your help.
