### ISSUE TITLE
Proplems with mixed case github usernames

### ISSUE THREAD

**Issue by BowlingX** [whoan/docker-build-with-cache-action#42]
Hi :) thank you for this action.

I'm getting an error during pushing. It seems like the repository name has to be lowercase and my github username is not lowercase and this is causing an issue:

```
Error parsing reference: "docker.pkg.github.com/..." is not a valid repository/tag: invalid reference format: repository name must be lowercase
```

I guess the issue is here: https://github.com/whoan/docker-build-with-cache-action/blob/master/entrypoint.sh#L67. It should lowercase the string.

**Comment by BowlingX** [comment]
Nevermind, I think it's allready solved by https://github.com/whoan/docker-build-with-cache-action/pull/41.

**Comment by whoan** [comment]
Hi @BowlingX . I will bump later today. Sorry for the inconvenience.
Thanks for reporting.

**Comment by whoan** [comment]
Bumped [v5.3.1](https://github.com/whoan/docker-build-with-cache-action/releases/tag/v5.3.1) with the fix. Regards.
