### ISSUE TITLE
Login on the docker.pkg.github.com registry

### ISSUE THREAD

**Issue by alban** [whoan/docker-build-with-cache-action#5]
The documentation on this [page](https://github.com/marketplace/actions/build-docker-images-using-cache) suggests it is possible to use docker.pkg.github.com with secrets.DOCKER_USERNAME and secrets.DOCKER_PASSWORD but the documentation does not say how to get those two secrets.

This is contradictory with [this page](https://help.github.com/en/github/managing-packages-with-github-packages/configuring-docker-for-use-with-github-packages#authenticating-with-the-github_token), we should be able to use `GITHUB_TOKEN` without username/password:

> If you are using a GitHub Actions workflow, you can use a GITHUB_TOKEN to publish and consume packages in GitHub Packages without needing to store and manage a personal access token.

Which one is true?

**Comment by whoan** [comment]
Hi @alban . You should manually set `DOCKER_USERNAME` and `DOCKER_PASSWORD` in your repo settings:

    Settings -> Secrets

with the values

    DOCKER_USERNAME=<your github username>
    DOCKER_PASSWORD=<your personal access token>

More info [here](https://help.github.com/en/github/managing-packages-with-github-packages/configuring-docker-for-use-with-github-packages#authenticating-to-github-packages).

**Comment by whoan** [comment]
Added more info to the README. Closing this. Feel free to reopen if you think I can do something else.
Regards.
