### ISSUE TITLE
Use to precache container actions?

### ISSUE THREAD

**Issue by JustinGrote** [whoan/docker-build-with-cache-action#51]
Hello,

I have this working and it downloads and works with cached images just fine using docker.
However, it appears for whatever reason the images don't stay cached on the runner, so when I try to run an image that uses the same dockerfile, it doesn't pull from cache and builds again.

Here is the example:
https://github.com/JustinGrote/Super-Duper-Linter/actions/runs/143165760/workflow
https://github.com/JustinGrote/Super-Duper-Linter/runs/793939119?check_suite_focus=true

**Comment by whoan** [comment]
@JustinGrote When you say that you run an image that uses the same dockerfile, I assume you are trying to build again without this action, so I wonder if you are passing the `--cache-from` switch to `docker build` which is needed to specify where to take cached from. That is what this action does: provide a list of caches to read from through `--cache-from`.

**Comment by JustinGrote** [comment]
@whoan I'm just trying to use the native Github Actions runner with a dockerfile specified

I worked around it by manually specifying the docker run command to use the tagged 'my_awesome_image' that gets built, I don't think there's a way to specify extra docker commands to an action, so I guess it'll have to do for now.

**Comment by JustinGrote** [comment]
@whoan I found a way to make this work while still running it as a native github action. You set up a test github action config and point it to the my_awesome_image container when running, and it will pick up the locally built container and run it rather than having to try to fetch it again or operate on a new dockerfile which doesn't pick up the cached stages.

Works great! Thanks for the awesome action
https://github.com/JustinGrote/Super-Duper-Linter/runs/797614138?check_suite_focus=true

**Comment by whoan** [comment]
@JustinGrote I think that using the `FULL_IMAGE_NAME` would also work. It is an output of the action. It is the fully qualified image name, with the registry prefixed.
