### ISSUE TITLE
Please warn that GitHub Registry public packages cannot be removed/replaced

### ISSUE THREAD

**Issue by fabio-d** [whoan/docker-build-with-cache-action#52]
Hello,
thanks for your effort in implementing this much needed action.

I have used it with GitHub's registry in a private test repository, and it worked.
However, when I tried to use it in a public repository, I was disappointed to find that it is impossible to neither update nor delete the cache. Not because of a bug of this action, but as a result of GitHub's controversial "[immutable public registry policy](https://help.github.com/en/packages/publishing-and-managing-packages/deleting-a-package)":

> To avoid breaking projects that may depend on your packages, you cannot delete an entire public package or specific versions of a public package.

The result of this hidden "trap" is that my public repository now has two old stale images, no longer even useful for the CI workflow, but they still appear prominently in the project's main page with no way to hide/delete them.

I suggest to add a notice in this action's readme file, to warn potential users like me about this pitfall. Something along the lines of

> If you are considering pushing the image to a **public** repository's GitHub Registry, please be aware that it will be impossible to ever delete or even update/rebuild the cache after the first run of this action, because of GitHub's policy regarding public packages. In other words, the cache will be immutable and not deletable. This limitation does not apply if the image is pushed to a **private** repository's GitHub Registry. For more information, refer to GitHub's Help about [Deleting a package](https://help.github.com/en/packages/publishing-and-managing-packages/deleting-a-package).

**Comment by whoan** [comment]
Hi @fabio-d . I like your suggestion. Could you please add it in the readme? I can do it later, but feel free to open a PR.
Thanks!

**Comment by whoan** [comment]
Closed by #53
