### ISSUE TITLE
Image is not pushed if `on:push` is disabled

### ISSUE THREAD

**Issue by alepez** [whoan/docker-build-with-cache-action#54]
I have a scheduled workflow:

```
on:
  schedule:
    - cron:  '0 4 * * *'
```

When the workflow runs, the image is built but not pushed.Here a log:

```
[Action Step] Pushing image...
Not pushing
```

I guess it's `_must_push` function returning false:

```
_must_push() {
  if [ "$INPUT_PUSH_IMAGE_AND_STAGES" = on:push ]; then
    [ "$GITHUB_EVENT_NAME" = push ]
    return
  fi

  if [ "$INPUT_PUSH_IMAGE_AND_STAGES" = on:pull_request ]; then
    [ "$GITHUB_EVENT_NAME" = pull_request ]
    return
  fi

  $INPUT_PUSH_IMAGE_AND_STAGES
}
```

Is this the expected behavior? I find it confusing.

**Comment by whoan** [comment]
Hi @alepez . I documented the `on:<event>` special flags to show how to use them. So far, those were kind of hidden features, and I am not sure why I didn't documented them before.

In a nutshell, that is NOT something you can disable, but you can set, for example, `push_image_and_stages: on:push` to push only if the workflow was triggered by a push. It is specially useful when your workflow can be triggered by different events.

I can help better if you share your settings.

**Comment by alepez** [comment]
Thanks @whoan. Now I think this wasn't an issue at all. I've just reviewed my workflow now and it seems I was inspecting the wrong github action log. When I was looking for the reason of the image not being pushed I thought it was `INPUT_PUSH_IMAGE_AND_STAGES` not being under my control (and being `on:push` for some reason). The `_must_push` function was even more confusing because `INPUT_PUSH_IMAGE_AND_STAGES` was evaluated both as a string and a command. Now, after having reviewed my workflow another time, I've seen that my bug wasn't related to `docker-build-with-cache-action`.

I'm sorry to have bothered you. At least the documentation has been improved, so next time I will be less confused (I hope).

**Comment by alepez** [comment]
By the way, I'm sure it's not related to your action, but in my repo's GitHub Packages, the package "Recent version" is always displaying the date of the first push, but when i pull it, I get the version I just built with `docker-build-with-cache-action`.
It seems to be a GitHub bug. but I cannot find any bug report about it. Do you know anything about this issue?

**Comment by whoan** [comment]
I don't know the reason of such an issue, but I agree that it seems a GitHub bug. As an example, in [the packages of a repo I use to test this action](https://github.com/whoan/hello-world/packages/209710), I also see misleading numbers.

I am glad you found the way to solve your issue, and you forced me to improve the readme :). Thanks!.
