### ISSUE TITLE
INFO: Won't be able to pull from private repos, nor to push to public/private repos

### ISSUE THREAD

**Issue by rawatnaresh** [whoan/docker-build-with-cache-action#55]
I've been trying to push my docker image to the private docker hub repo. But it's saying it cannot push to the private repos. Does my repo have to be public to use this?
i'm using `docker-build-with-cache-action@v5`

**Comment by whoan** [comment]
@rawatnaresh You can as long as you provide valid credentials. That log is shown when you can't login to the registry whatever reason.
