### ISSUE TITLE
Could not set namespace

### ISSUE THREAD

**Issue by Balgorn** [whoan/docker-build-with-cache-action#60]
Hello!

just wanted to know if I have to change something after the latest changes in the parsing of the namespace. 
For me personally the action worked before this change, but now I get 'Could not set namespace' on each build.

Context: I have a registry on gcr and I try to build images with custom tags

Hints and Tips would be appreciated.

**Comment by whoan** [comment]
Thanks for reporting the issue @Balgorn . It seems like [this commit](https://github.com/whoan/docker-build-with-cache-action/commit/1a6822c74c8f72b31ad41f33d8f03cdd437eda0e) broke it.

**Comment by Balgorn** [comment]
Seems likely I am no expart in jq.  A hotfix right now is to prefix the image_name with your project Id followed by /

**Comment by whoan** [comment]
The last version I have just created should fix the issue (v5/v5.4.1). Is it still failing?

**Comment by Balgorn** [comment]
Yes with the new version it is working again. Thank you!

**Comment by hackinteach** [comment]
Hi, I'm still facing this issue. I'm using v5 and just tried out v5.7.0 and still not working.
