### ISSUE TITLE
Specify ECR repository name

### ISSUE THREAD

**Issue by TanAidan** [whoan/docker-build-with-cache-action#64]
Is there a way to specify the specific ECR repo that we want to pull/cache/push the docker to?

**Comment by whoan** [comment]
@TanAidan Currently, you can't specify custom repos, it uses the `image_name` and appends `-stages` for the stages.

**Comment by whoan** [comment]
This is not going to be implemented for the moment so I am closing this. Feel free to reopen if it becomes a must for some scenarios.
