### ISSUE TITLE
"denied: Resource not accessible by integration" 

### ISSUE THREAD

**Issue by peterbe** [whoan/docker-build-with-cache-action#65]
First of all, it might be user error because I don't quite understand the `username` part.

I'm trying to use this action like this:

```yml
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          dockerfile: docker/images/kuma_base/Dockerfile
          # We'll only want to do this if it's a master build. XXX How do you do that?
          # push_image_and_stages: false
          username: mdn
          password: "${{ secrets.GITHUB_TOKEN }}"
          # XXX Apparently, ghcr.io is the new name. Does that work better?
          registry: docker.pkg.github.com
          # XXX Should this be mdnwebdocs/kuma???
          image_name: kuma
```
And it works when I use `push_image_and_stages: false` but that's cheating because that's not actually pushing anything. 

We're developers of an organization. The organization is github.com/mdn and I tried putting the `username` to `mdn` but I also tried setting it to my personal GitHub username `peterbe`.

Note that it says "Login Succeeded"...

```
2020-09-08T12:41:07.4840145Z [Action Step] Checking required input...
2020-09-08T12:41:07.4840337Z 
2020-09-08T12:41:07.4840505Z [Action Step] Log in to registry...
2020-09-08T12:41:07.5558319Z WARNING! Your password will be stored unencrypted in /github/home/.docker/config.json.
2020-09-08T12:41:07.5558652Z Configure a credential helper to remove this warning. See
2020-09-08T12:41:07.5559599Z https://docs.docker.com/engine/reference/commandline/login/#credentials-store
2020-09-08T12:41:07.5559720Z 
2020-09-08T12:41:07.5559884Z Login Succeeded
2020-09-08T12:41:07.5559953Z 
2020-09-08T12:41:07.5560115Z [Action Step] Pulling image...
2020-09-08T12:41:07.7037678Z 
2020-09-08T12:41:07.7038264Z [Action Step] Building image...
2020-09-08T12:41:07.7069974Z + docker build --tag + tee build-output.log
2020-09-08T12:41:07.7070427Z my_awesome_image --file ./docker/images/kuma_base/Dockerfile .
2020-09-08T12:41:08.6841336Z Sending build context to Docker daemon  44.05MB
2020-09-08T12:41:08.6841687Z 
2020-09-08T12:41:08.6913172Z Step 1/23 : FROM python:3.8.0-slim@sha256:7df1fd6bb894e03b488c01fd05eaa4dd677f5b57d800c209f7f0af9867137df9
```

But it appears to be failing here with: `denied: Resource not accessible by integration`

```
2020-09-08T12:49:03.9547247Z Successfully built d0fc99d469df
2020-09-08T12:49:03.9629911Z Successfully tagged my_awesome_image:latest
2020-09-08T12:49:03.9635224Z + set +x
2020-09-08T12:49:03.9635325Z 
2020-09-08T12:49:03.9635937Z [Action Step] Tagging image...
2020-09-08T12:49:03.9636250Z Tag: docker.pkg.github.com/mdn/kuma/kuma:latest
2020-09-08T12:49:03.9922829Z 
2020-09-08T12:49:03.9924019Z [Action Step] Pushing image...
2020-09-08T12:49:03.9924361Z Pushing: latest
2020-09-08T12:49:04.0286124Z The push refers to repository [docker.pkg.github.com/mdn/kuma/kuma]
2020-09-08T12:49:04.0437931Z bf0de1c6f4ae: Preparing
2020-09-08T12:49:04.0438844Z 68edad45c259: Preparing
...snip...
2020-09-08T12:49:04.0448413Z b67d19e65ef6: Waiting
2020-09-08T12:49:04.2831618Z denied: Resource not accessible by integration
2020-09-08T12:49:04.2870564Z 
2020-09-08T12:49:04.2909139Z [Action Step] Log out from registry...
2020-09-08T12:49:04.3102087Z Removing login credentials for docker.pkg.github.com
```

Hopefully this URL is permanent: https://github.com/mdn/kuma/pull/7456/checks?check_run_id=1085912050

**Comment by peterbe** [comment]
[According to this documentation](https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#permissions-for-the-github_token) the `GITHUB_TOKEN` should have write access to `packages`.

**Comment by whoan** [comment]
Hi @peterbe . I can take a look at this later today. The only thing to mention is that it seems to be a problem with permissions.
I will try to create an organization and try the action there as I think I didn't test such a scenario. Could you please check the permissions under Settings > Actions > Actions permissions ?

**Comment by whoan** [comment]
@peterbe I tested both with my user and with a company's user and it worked with both of them:

- https://github.com/whoan-company/hello-world/runs/1087325476 ([action example](https://github.com/whoan-company/hello-world/blob/master/.github/workflows/git-hub.yml))
- https://github.com/whoan-company/hello-world/runs/1087342553 ([action example](https://github.com/whoan-company/hello-world/blob/change-for-company/.github/workflows/git-hub.yml))

**Comment by peterbe** [comment]
> Could you please check the permissions under Settings > Actions > Actions permissions ?

<img width="710" alt="Screen Shot 2020-09-08 at 2 05 21 PM" src="https://user-images.githubusercontent.com/26739/92512177-66eb0980-f1dc-11ea-834a-6f47b34ffcb2.png">

**Comment by peterbe** [comment]
Could it be because my PR is from fork `peterbe` to master inside the upstream `mdn`. I'll try to make a PR within the repo rather than from a user to an org.

**Comment by peterbe** [comment]
In my experiment, I was trying to *push* to the GitHub Container Registry from within a PR (fork:topic-branch to origin:master). Perhaps that just isn't allowed and it's just sad that the error message isn't better. 

In reality, what we're hoping to end up is that we'll only *push* to the registry on commits to `master` but all the various PRs from people *to* the `origin/master` will be using *read* to get caching layers.

**Comment by whoan** [comment]
@peterbe  what about this in your workflow:

    on:
      push:
        branches:
          - master
      pull_request:
        branches:
          - master

and this in the action:

    push_image_and_stages: on:push

**Comment by peterbe** [comment]
I don't know exactly what I did but now it's kinda working! https://github.com/mdn/kuma/packages/390064
Your action pushed this. 

What I now need to figure out is how to actually use it in consecutive `docker-compose build`.

**Comment by whoan** [comment]
@peterbe Could you please elaborate on those consecutive `docker-compose build`s you need. You need to use the generated image in further actionn steps? If so, notice the action outputs the resulting image name.

**Comment by peterbe** [comment]
> consecutive `docker-compose build`s you need. You need to use the generated image in further actionn steps?

No, our CI does this:

1. `docker-compose build`
1. `docker-compose run something`
1. `docker-compose run somethingelse`

...for every PR. But the `docker-compose build` takes a long time. So we're hoping we can benefit from `docker-build-with-cache-action` to get the second `docker-compose build` to leverage the docker layer caching. 

For example, on my laptop, on a clean docker layer cache, it takes 4m40s to run `docker-compose build` but the second time I run it it takes 17s. 

But perhaps that's not `docker-build-with-cache-action` and images work. (I'm not a docker or docker-compose expert!)
Perhaps it's wrong to bother pushing the built images to any registry and just have the "stages" pushed to the cache without bothering with any registry.

**Comment by whoan** [comment]
@peterbe This action is meant to read a Dockerfile and build one image at a time. Maybe it's time to support reading a compose file. I will give it a try soon.

**Comment by whoan** [comment]
@peterbe It seems that supporting to read from a compose file is a big effort and would make the script way more complex.
On the other hand, you can set a step with this action for each image you need to build (based on your compose file), and you should accomplish same functionality. Closing this as I think reading from a compose file shouldn't be mandatory for that reason.

**Comment by peterbe** [comment]
Thanks for your help @whoan !
I've come to appreciate that I still have a lot to learn with Docker stuff. 

`docker-compose` is just an abstraction (a YAML file) for typing `docker` commands plus that thing that is able to start up multiple containers across a range of ports and stuff. 

I'm wondering, since `docker-compose build` is just a wrapper for `docker build` but with the params specified in the `docker-compose.yml`, if I use `docker-build-with-cache-action` it would use the GitHub Action Cache to make the consecutive `docker build` faster.

**Comment by whoan** [comment]
@peterbe I have finally added support to compose files: https://github.com/whoan/docker-build-with-cache-action/pull/78
Feel free to check if it fits your needs.

**Comment by peterbe** [comment]
Cheers! I must admit that I lost my momentum with this work. But by the time I get back into it, perhaps your PR will have been merged and release :) Looking forward to it!
