### ISSUE TITLE
push_git_tag does not work with ECR

### ISSUE THREAD

**Issue by lehno** [whoan/docker-build-with-cache-action#72]
I can clearly see in the plugin logs it pushes the tag from image_tag but it does not push the git tag.

**Comment by lehno** [comment]
I was able to push latest and git tag using `image_tag: latest,${{ github.sha }}`
I had to remove the push_git_tag from my yaml

**Comment by whoan** [comment]
Sorry I still couldn't see your issue @lehno .
Will definitively take a look at it later today. Thanks!

**Comment by whoan** [comment]
@lehno Looking at your second comment I think you wanted the action to push the hash of the last commit with `push_git_tag`, right?
`push_git_tag` is meant to push any tag you create with `git tag`, eg: v1.0.0 and the like.

It would be helpful if you have a public repo to see the logs of the action.

**Comment by lehno** [comment]
Aahh, I see now, I thought that If I wanted the git.sha image tag pushed, I would need this option set to true. My bad in this case
