### ISSUE TITLE
Downloading cache freezing and consuming 10 times for time to build

### ISSUE THREAD

**Issue by lehno** [whoan/docker-build-with-cache-action#77]
I have been using this action for a while and my image takes 2 min to build using cache.
But sometimes I see this: 
![image](https://user-images.githubusercontent.com/5764569/102628981-72868e80-4142-11eb-9a35-92bfa4b9e1d3.png)
15 min stuck on some internal function. And GitHub charged me this full amount.
Any ideas?

**Comment by whoan** [comment]
HI @lehno . I don't understand what it means when you say: _GitHub charged me this full amount_. Could you please elaborate?

I will need more details in order to help. Thanks for using the action :)

**Comment by whoan** [comment]
@lehno  I hadn't noticed in your image the 15 minutes of difference between "Pull complete" and the "Verifying checksum" steps.
I don't know what is going on there but I am pretty sure it has nothing to do with this action.

Do you know which image is downloading when it happens? Maybe the image is huge and it takes a lot of time to do the checksum according to how loaded GitHub servers are; I am just trying to guess what is going on anyway. I would ask GitHub support if it only happens sporadically.

Closing this as unrelated.

**Comment by lehno** [comment]
Hey, the image is 89Mb, it happens every lets say 20 deployments. The only info I have is line 88 to 89. It was there for 15 min, it can be a Github problem I agree. Just posted here because maybe someone else had a similar problem or you could have some thoughts about it. For me the biggest problem is the time I'm paying to Github Actions when this happens.
