### ISSUE TITLE
Support for AWS ECR public registry

### ISSUE THREAD

**Issue by AntoineAugusti** [whoan/docker-build-with-cache-action#79]
Hello!

Thanks for this nice action. Following #27, would it be possible to support AWS ECR public registry? This has been launched in [December 2020](https://aws.amazon.com/about-aws/whats-new/2020/12/announcing-amazon-ecr-public-and-amazon-ecr-public-gallery/).

The relevant documentation is here: https://docs.aws.amazon.com/AmazonECR/latest/public/public-registries.html#public-registry-auth

The auth command is
> aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

I think what's needed is:
- updating the regex to match the public endpoint (or create a new detection mechanism)
- bump the AWS CLI to be able to use the `ecr-public` namespace

**Comment by whoan** [comment]
Hi @AntoineAugusti . Yes, I this AWS ECR public registry should be supported. Let me give it a try at the weekend.  

Thanks

**Comment by AntoineAugusti** [comment]
That's fantastic! If you're short on time, tell me. I should be able to write up a PR in January for this.

**Comment by whoan** [comment]
I took a look at it and it seems like an easy change. My only concern is that I need to find some way to get the AWS region when we use ECR public. In the private one, I was taking the region from the INPUT_REGISTRY variable, but in the public one it's not present anymore: public.ecr.aws

**Comment by AntoineAugusti** [comment]
The [documentation](https://docs.aws.amazon.com/AmazonECR/latest/public/public-registries.html#public-registry-auth) says that the authentication should always be done on `us-east-1`

> When authenticating to a public registry, always authenticate to the us-east-1 Region when using the AWS CLI.

**Comment by whoan** [comment]
That is great news @AntoineAugusti . Thanks for your quick reply!

**Comment by whoan** [comment]
I could not finish this feature yet because I am having an issue pulling all tags from public ECR.

This works:

    docker pull public.ecr.aws/p6n4p0s0/hello-world:latest

But this doesn't:

    docker pull --all-tags  public.ecr.aws/p6n4p0s0/hello-world

I will try to give it another try before 2021!

**Comment by whoan** [comment]
Hey @AntoineAugusti . Could you give v.5.9.0 a try? I added support to AWS ECR Public and it was trickier than expected but acoording to [this test](https://github.com/whoan/hello-world/runs/1635059562) it is working now.

Feel free to reopen this issue if you find any issue.

**Comment by AntoineAugusti** [comment]
@whoan Thanks for implementing this quickly! I'll report it here as soon as I can
