### ISSUE TITLE
Multi-Platform Docker Builds

### ISSUE THREAD

**Issue by mdegis** [whoan/docker-build-with-cache-action#82]
Currently, I did not find any settings or variables that could be used to trigger multi-platform Docker builds.

With M1 MBPs, arm64 architecture is (and will be more) mainstream IMO.
Is this something you considered to support near-future?

**Comment by whoan** [comment]
You have a very valid point @mdegis . I will take a look sometime soon.
I think we need `docker buildx` to do so. Feel free to make suggestions/PR.

**Comment by whoan** [comment]
@mdegis I think this action does what you want: https://github.com/docker/setup-buildx-action

**Comment by hingston** [comment]
Can docker/setup-buildx-action be used with this action? I can't see how

**Comment by lukasa1993** [comment]
any love for this?

**Comment by whoan** [comment]
I gave it a try to this one (again) and still think it's a very big effort. Are there many people looking for this feature? If so, could you please share some use cases?

**Comment by inodb** [comment]
We are also looking for this feature. Many people use the docker setup of our tool cBioPortal (https://github.com/cBioPortal/cbioportal) on their local machines during development

**Comment by whoan** [comment]
I am not going to implement this for the moment. Closing for now.

**Comment by whoan** [comment]
Please see [v8](https://github.com/whoan/docker-build-with-cache-action/tree/v8). Now this action uses BuildKit by default so you can provide any option to `buildx` through `build_extra_args` input.
Hope that helps.

**Comment by inodb** [comment]
Awesome!! Thanks so much @whoan !
