### ISSUE TITLE
Bug when pushing stages if docker-compose file specifies two (or more!) images

### ISSUE THREAD

**Issue by silky** [whoan/docker-build-with-cache-action#87]
This is the bug:

![image](https://user-images.githubusercontent.com/129525/106123148-79e18480-6151-11eb-911e-93b7e86f0333.png)

If I was to guess, it's because in a few places in entrypoint.sh you expect only one image:

```
entrypoint.sh
60:    mapfile -t images < <(grep -Po "(?<=_image=\")${INPUT_USERNAME}/[^\"]+" "$parsed_yaml")
62:    mapfile -t images < <(grep -Po "(?<=_image=\")${INPUT_REGISTRY}/[^\"]+" "$parsed_yaml")
95:  grep -Po "(?<=services_)[^_]+(?=.+$image_name.+)" "$parsed_yaml"
101:  grep -Po "(?<=services_${service_name}_build_context=\")[^\"]+" "$parsed_yaml"
107:  grep -Po "(?<=services_${service_name}_build_dockerfile=\")[^\"]+" "$parsed_yaml"
```

**Comment by silky** [comment]
glancing at the source, i can't even see how one of these commands could be run after logout is run, however ....

**Comment by silky** [comment]
it's because it happens when pushing the stages i think

**Comment by silky** [comment]
hey @whoan thanks so much for taking a look

i just tried this, and i don't think it's working; here's more details on the error:

```
Pushing stage: 1
The push refers to repository [ghcr.io/....]
..: Preparing
..: Preparing
..: Preparing
..: Preparing
..: Preparing
..: Preparing
..: Waiting
..: Waiting
..: Waiting
..: Waiting
...: Layer already exists
...: Layer already exists
...: Layer already exists
1: digest: sha256:... size: 3659

[Action Step] Log out from registry...
Removing login credentials for ghcr.io
grep: the -P option only supports a single pattern
```

so the crash, as i understand it, happens in the second step of pushing the stages:

```
_push_image_stages() {
  local stage_number=1
  local stage_image
  for stage in $(_get_stages); do
    echo -e "\nPushing stage: $stage_number"
    stage_image=$(_get_full_stages_image_name):$stage_number
    docker tag "$stage" "$stage_image"
    docker push "$stage_image"
    stage_number=$(( stage_number+1 ))
  done

  # push the image itself as a stage (the last one)
  echo -e "\nPushing stage: $stage_number"
  stage_image=$(_get_full_stages_image_name):$stage_number
  docker tag "$DUMMY_IMAGE_NAME" "$stage_image"
  docker push "$stage_image"
}
```

because i never see that second "Pushing stage: 2" ... happen

i don't understand what could be happening

**Comment by silky** [comment]
note that your test docker-compose file doesn't test this scenario - https://github.com/whoan/hello-world/blob/master/docker-compose.yml - because it only has one image file for github, whereas in my example i have two:

```
(base) 07:49 am noon φ thing (cached-builds) cat docker-compose.yml | grep 'ghcr.io'
    image: ghcr.io/silky/thing-some-supporting-container
    image: ghcr.io/silky/thing
```

**Comment by whoan** [comment]
@silky But I have two images for Doker Hub in my test compose file. I wonder if it is because one image name in your example is the prefix of the other image name. Will check in that direction.

**Comment by silky** [comment]
Thanks @whoan ; that fixed it :)
