### ISSUE TITLE
Pass Multiple --build-arg to Docker file. Only First one is picked 

### ISSUE THREAD

**Issue by ahmadfaraz629** [whoan/docker-build-with-cache-action#94]
Hi I need to pass 3 arguments to the docker file I am using the action like this.

![image](https://user-images.githubusercontent.com/17162601/109562673-81090300-7b00-11eb-8e9a-08224986a6be.png)

`    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        password: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        registry: "${{ steps.login-ecr.outputs.registry }}"
        image_name: ${{ env.ECR_REPOSITORY }}
        image_tag: ${{ env.IMAGE_TAG }}
        build_extra_args: "--build-arg=PARAM=value --build-arg=PARAM1=value1 --build-arg=PARAM2=value2 "
`

I have also tried using this.
![image](https://user-images.githubusercontent.com/17162601/109562703-8a926b00-7b00-11eb-95fc-7b2c6e8f6de7.png)

`    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        password: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        registry: "${{ steps.login-ecr.outputs.registry }}"
        image_name: ${{ env.ECR_REPOSITORY }}
        image_tag: ${{ env.IMAGE_TAG }}
        build_extra_args: "--build-arg PARAM=value --build-arg PARAM1=value1 --build-arg PARAM2=value2 "
 `
 
 I am following this from the docker as you can see down that we can pass multiple build args to it.
 
![image](https://user-images.githubusercontent.com/17162601/109562286-0213ca80-7b00-11eb-9339-cbdd9822c951.png)

 
 Issue is that only the first one is being passed to the Dockerfile.

**Comment by whoan** [comment]
Hi @ahmadfaraz629 . That's strange. My [build has just succeeded](https://github.com/whoan/hello-world/runs/2013555336) with the same extra args:

    + docker build --cache-from=whoan/hello-world-stages:1 --cache-from=whoan/hello-world-stages:2 --cache-from=whoan/hello-world-stages:3 --cache-from=whoan/hello-world-stages:4 --cache-from=whoan/hello-world-stages:5 --tag my_awesome_image --file ./Dockerfile --build-arg=PARAM=value --build-arg=PARAM1=value1 --build-arg=PARAM2=value2 .

Then I have a WARNING because I am not consuming those args, but that's expected:

     Warning:  One or more build-args [PARAM PARAM1 PARAM2] were not consumed

**Comment by whoan** [comment]
The tests shows that the action is working correctly. Feel free to reopen with action output to debug further.
