### ISSUE TITLE
Unable to export a variable named NAMESPACE in GITHUB_ENV

### ISSUE THREAD

**Issue by erran** [whoan/docker-build-with-cache-action#97]
Setting a variable called `NAMESPACE` caused some confusion when this action started failing suddenly using a private ECR repository (without a namespace).

I managed to track it down to this code in [`_set_namespace`](https://github.com/whoan/docker-build-with-cache-action/blob/86b305ae784f/docker-build.sh#L66-L70)
```bash
    fi
    # aws-ecr (private) does not need a namespace
  fi
  # set namespace to all lower, capital letters are not supported
  NAMESPACE=${NAMESPACE,,}
```

I simply renamed the environment variable in my case but wanted to create an issue for anyone who gets stuck on this (feel free to close ❤️).

I think one possible work around would be to override the `NAMESPACE` variable and set it to empty for the specific step using this action. Otherwise it may be worth adding a flag on the action or making environment variables use an uncommon prefix.

**Comment by zainab81** [comment]
Ok

**Comment by erran** [comment]
Closing this — meant to close it after opening. If the maintainers think it makes sense to create an alt name for that environment variable or not 🤷🏽‍♂️
